version: '2'

services:
  lunchbuddy_mongo:
    image: mongo:3.4
    container_name: 'lunchbuddy_mongo'
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  lunchbuddy_app:
    image: lunchbuddy/server
    container_name: 'lunchbuddy_app'
    hostname: lunchbuddy
    ports:
      - "8080:8080"

volumes:
  mongodata: