version: '2'

services:
  lunchbuddy_mongo:
    image: mongo:3.4
    container_name: 'lunchbuddy_mongo'
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: